# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: check-yaml
#      - id: check-json
      - id: check-added-large-files
#      - id: pretty-format-json
      - id: debug-statements
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.9.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        entry: docker exec chillapi-api bash -c ". venv/bin/activate && venv/bin/pip freeze > requirements.txt && chown -Rf 1000:1000 requirements.txt"
        always_run: true
        require_serial: true
        types_or: [ python ]
      - id: black
        name: black
        language: system
        entry: docker exec chillapi-api bash -c ". venv/bin/activate && venv/bin/black -t py38 -q -l 150 chillapi/"
        always_run: true
        require_serial: true
        types_or: [ python ]
      - id: flake8
        name: flake8
        language: system
        entry: docker exec chillapi-api bash -c ". venv/bin/activate && venv/bin/flake8 --max-line-length 150 --max-complexity 15 chillapi"
        always_run: true
        require_serial: true
        types_or: [ python ]
      - id: testing set time
        name: testing set time
        language: system
        entry: docker exec chillapi-api bash -c ". venv/bin/activate && venv/bin/python -m unittest tests.settime.api tests.settime.app.config"
        always_run: true
        require_serial: true
        types_or: [ python ]
      - id: testing run time
        name: testing run time
        language: system
        entry: docker exec chillapi-api bash -c ". venv/bin/activate && venv/bin/python -m unittest tests.runtime.api_test"
        always_run: true
        require_serial: true
        types_or: [ python ]
      - id: fix_permissions
        name: fix_permissions
        language: system
        entry: docker exec chillapi-api chown -Rf 1000:1000 .
        always_run: true
        require_serial: true
        types_or: [ python ]
