"""master/autogenerated

Revision ID: 7157c7fb3fd3
Revises:
Create Date: 2021-03-27 21:28:38.932926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '7157c7fb3fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS book_category (
               id INTEGER PRIMARY KEY,
               name TEXT NOT NULL,
               created_at datetime,
               created_by TEXT,
               updated_at datetime,
               updated_by TEXT,
               deleted_at datetime,
               deleted_by TEXT
            );
            """
        )
    )

    conn.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS book (
               id INTEGER PRIMARY KEY,
               book_category_id int NOT NULL,
               name TEXT NOT NULL,
               asin TEXT NOT NULL,
               created_at datetime,
               created_by TEXT,
               updated_at datetime,
               updated_by TEXT,
               deleted_at datetime,
               deleted_by TEXT,
               FOREIGN KEY(book_category_id) REFERENCES book_category(id),
               UNIQUE(asin)
            );
            """
        )
    )

    conn.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS author (
               id INTEGER PRIMARY KEY,
               name TEXT NOT NULL,
               asin TEXT NOT NULL,
               created_at datetime,
               created_by TEXT,
               updated_at datetime,
               updated_by TEXT,
               deleted_at datetime,
               deleted_by TEXT,
               UNIQUE(asin)
            );
            """
        )
    )

    conn.execute(
        text(
            """
            CREATE TABLE book_has_author (
              book_id  int REFERENCES book (id),
              author_id int REFERENCES author (id),
              UNIQUE(book_id, author_id)
            );
            """
        )
    )



    conn.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS dummy_create (
               id INTEGER PRIMARY KEY,
               name TEXT,
               creation datetime
            );
            """
        )
    )

    conn.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS dummy (
               id INTEGER PRIMARY KEY,
               name TEXT
            );
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO book_category (id, name, created_at) VALUES
            (1, '{"en-US":"Suspense"}', CURRENT_TIMESTAMP)
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO book (id, book_category_id, name, asin, created_at) VALUES
            (1, 1, 'The Dark Tower', '1444723502', CURRENT_TIMESTAMP)
            """
        )
    )
    conn.execute(
        text(
            """
            INSERT INTO author (id, name, asin, created_at) VALUES
            (1, '{"en-US": "Stephen King"}', 'X23XX', CURRENT_TIMESTAMP)
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO book_has_author (author_id, book_id) VALUES (1, 1)
            """
        )
    )


pass


def downgrade():
    conn = op.get_bind()
    conn.execute(
        text(
            """
            DROP TABLE dummy
            """
        )
    )
    conn.execute(
        text(
            """
            DROP TABLE dummy_create
            """
        )
    )
    conn.execute(
        text(
            """
            DROP TABLE book_category
            """
        )
    )
    conn.execute(
        text(
            """
            DROP TABLE book_has_author
            """
        )
    )
    conn.execute(
        text(
            """
            DROP TABLE author
            """
        )
    )
    conn.execute(
        text(
            """
            DROP TABLE book
            """
        )
    )
    pass
