name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - 'feature/*'
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U wheel --user
          pip install -r requirements.txt
#      - name: Lint code (BLACK)
#        run: |
#          black -l 150 src/ test/
#      - name: Lint code (flake8)
#        run: |
#          flake8 --max-line-length 150 --max-complexity 10 src test
      - name: Testing
        run: python -m unittest tests.app.config tests.api
